#!/usr/bin/env python3
#
#  * Filename :    IMem_script.py

#  * Date     :    1-1-2022

#  *

#  *

#  * Description:  Loading the machine code from .txt file into Boot Memory

#  *

#  *********************************************************************/

import sys
binfile = sys.argv[-2]
cfile   = sys.argv[-1]

src_file = open(binfile , "r")

des_file = open(cfile , "w")

des_file.write("/********************************************************* \n")
des_file.write(" * Filename :    imem.c                                    \n")
des_file.write(" * Date     :    31-12-2021                                \n")
des_file.write(" * Author   :    Muhammad Tahir                            \n")
des_file.write(" *                                                         \n")
des_file.write(" * Description: This is an autogenerated file using Python \n")             
des_file.write(" * script. Instruction memory contents that are written to \n")
des_file.write(" * the flash memory and are copied by the bootloader to    \n")
des_file.write(" * the instruction memory.                                 \n")
des_file.write(" ********************************************************/ \n")

des_file.write("#include <inttypes.h>                                      \n")
des_file.write("#include \"SPI_Flash.h\"                                \n \n")


index = 0

for line in src_file:

    i = str(index)

    des_file.write(" "*27+"0x"+ line[0] + line[1] +  ", 0x" + line[2] + line[3]   
    + ", 0x" + line[4] + line[5] + ", 0x" + line[6] + line[7] + "," + "\n")

    index+=1

des_file.write("}; \n \n")
des_file.write("uint32_t imem_size = ARRAY_SIZE(Imem_Content);")

des_file.close()

src_file.close()