create_clock -name clock2 -period 10 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports step1step]
set_property IOSTANDARD LVCMOS33 [get_ports io_pwm_low]
set_property IOSTANDARD LVCMOS33 [get_ports homing_switch_1]
set_property IOSTANDARD LVCMOS33 [get_ports homing_switch_2]
set_property IOSTANDARD LVCMOS33 [get_ports io_spi_clk]
set_property IOSTANDARD LVCMOS33 [get_ports io_spi_cs]
set_property IOSTANDARD LVCMOS33 [get_ports io_spi_miso]
set_property IOSTANDARD LVCMOS33 [get_ports io_spi_mosi]
set_property IOSTANDARD LVCMOS33 [get_ports io_uart_rx]
set_property IOSTANDARD LVCMOS33 [get_ports io_uart_tx]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports led1]
set_property IOSTANDARD LVCMOS33 [get_ports led2]
set_property IOSTANDARD LVCMOS33 [get_ports io_dir_m1]
set_property IOSTANDARD LVCMOS33 [get_ports io_dir_m2]
set_property IOSTANDARD LVCMOS33 [get_ports step2step]
set_property IOSTANDARD LVCMOS33 [get_ports pen_servo_control]
set_property PACKAGE_PIN E3  [get_ports clock]
set_property PACKAGE_PIN G16 [get_ports step1step]
set_property PACKAGE_PIN H14 [get_ports io_pwm_low]
set_property PACKAGE_PIN N16 [get_ports led1]
set_property PACKAGE_PIN N15 [get_ports led2]
set_property PACKAGE_PIN D14 [get_ports homing_switch_1]
set_property PACKAGE_PIN F16 [get_ports homing_switch_2]
set_property PACKAGE_PIN D17 [get_ports io_spi_clk]
set_property PACKAGE_PIN E17 [get_ports io_spi_cs]
set_property PACKAGE_PIN G18 [get_ports io_spi_miso]
set_property PACKAGE_PIN F18 [get_ports io_spi_mosi]
set_property PACKAGE_PIN D18 [get_ports io_uart_rx]
set_property PACKAGE_PIN C17 [get_ports io_uart_tx]
set_property PACKAGE_PIN R13 [get_ports reset]
set_property PACKAGE_PIN E18 [get_ports io_dir_m1]
set_property PACKAGE_PIN G17 [get_ports io_dir_m2]
set_property PACKAGE_PIN E16 [get_ports step2step]
set_property PACKAGE_PIN G13 [get_ports pen_servo_control]


#set_property MARK_DEBUG true [get_nets io_pwm_high]
#set_property MARK_DEBUG true [get_nets io_pwm_low]

#create_debug_core u_ila_0 ila
#set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
#set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
#set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
#set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
#set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
#set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
#set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
#set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
#set_property port_width 1 [get_debug_ports u_ila_0/clk]
#connect_debug_port u_ila_0/clk [get_nets [list clock_IBUF_BUFG]]
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
#set_property port_width 1 [get_debug_ports u_ila_0/probe0]
#connect_debug_port u_ila_0/probe0 [get_nets [list io_pwm_high_OBUF]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
#set_property port_width 1 [get_debug_ports u_ila_0/probe1]
#connect_debug_port u_ila_0/probe1 [get_nets [list io_pwm_low_OBUF]]
#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets soc_clock]


#create_debug_core u_ila_0 ila
#set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
#set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
#set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
#set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
#set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
#set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
#set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
#set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
#set_property port_width 1 [get_debug_ports u_ila_0/clk]
#connect_debug_port u_ila_0/clk [get_nets [list clock_IBUF_BUFG]]
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
#set_property port_width 1 [get_debug_ports u_ila_0/probe0]
#connect_debug_port u_ila_0/probe0 [get_nets [list io_pwm_high_OBUF]]
#create_debug_port u_ila_0 probe
#set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
#set_property port_width 1 [get_debug_ports u_ila_0/probe1]
#connect_debug_port u_ila_0/probe1 [get_nets [list io_pwm_low_OBUF]]
#set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
#set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
#set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
#connect_debug_port dbg_hub/clk [get_nets clock_IBUF_BUFG]
