name: CI

on:
  # Runs on Every Push
  push:
    branches: [ "UETRV_ESoC_v2" ]
  # Runs on Pull Requests
  pull_request:
  workflow_dispatch:

jobs:
  run_tb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run testbench
        run: make run_tb

      #- name: Install dependencies
      #  run: |
      #    sudo mkdir -p ${{ env.PDK_ROOT }}
      #    sudo chown -R $USER:$USER ${{ env.PDK_ROOT }}
      #    make install
      #    make openlane
      #    make pdk-with-volare
